micronaut:
  application:
    name: msVehicle
datasources:
  default:
    url: jdbc:postgresql://localhost:5444/ms-vehicle
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    password: '123456'
    username: admin
    schema-generate: CREATE_DROP
jpa:
  default:
    packages-to-scan:
      - 'br.com.gustavodinniz'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true
netty:
  default:
    allocator:
      max-order: 3
